apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-docker-app
  labels:
    app: node-docker-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: node-docker-app
  template:
    metadata:
      labels:
        app: node-docker-app
    spec:
      containers:
      - name: docker-app
        image: docker/getting-started
        volumeMounts:
        - name: db-connection
          mountPath: /opt
        ports:
        - containerPort: 3000
      volumes:
      - name: db-connection
        configMap:
          name: test-cm

